###
# The database contains all the information about hosts and 
# partitions that this program monitors.
###
database = './dfstat.db'

###
# Location of the ssh config information
###
sshconfig_file = '~/.ssh/config'

###
# Number of seconds between polling.
###
time_interval = 3600

###
# Down reporting: this is the number of consecutive times that
# a host can be non-responsive before we report it as down.
###
num_allowed_failures = 1
message_repeat = 86340 # One minute less than a day.
failure_message = "{} is non-responsive."

###
# Number of samples in the current window.
###
window_size = 50

###
# Where to send the alarms.
###
notification_address = [ 'hpc@richmond.edu', '8044959650@vtext.com' ]

###
# Parameters for statistical analysis
###
hosts = [   {host = 'alexis', partition = ["ERROR", "/home", "/usr/local"]}, 
            {host = 'adam', partition = ["ERROR", "/home", "/"]}, 
            {host = 'spydur', partition = ["ERROR", "/home", "/usr/local", "/scratch"]},
            {host = 'billieholiday', partition = ["ERROR", "/home", "/"]},
            {host = 'justin', partition = ["ERROR", "/home", "/", "/scr", "/data"]},
            {host = 'boyi', partition = ["ERROR", "/", "/scr", "/data"]},
            {host = 'camryn', partition = ["ERROR", "/home", "/"]},
            {host = 'cooper', partition = ["ERROR", "/home", "/"]},
            {host = 'erica', partition = ["ERROR", "/home", "/", "scratch"]},
            {host = 'hamilton', partition = ["ERROR", "/home", "/"]},
            {host = 'irene', partition = ["ERROR", "/home", "/"]},
            {host = 'kevin', partition = ["ERROR", "/home", "/"]},
            {host = 'mayer', partition = ["ERROR", "/home", "/"]},
            {host = 'michael', partition = ["ERROR", "/home", "/"]},
            {host = 'sarah', partition = ["ERROR", "/"]},
            {host = 'thais', partition = ["ERROR", "/home", "/"]},
            {host = 'spiderweb', partition = ["/home", "/", "/var", "/opt", "/usr/local"]},
            {host = 'enterprise', partition = ["ERROR", "/home", "/"]}, 
            {host = "trueuser", partition = ["ERROR", "/", "/var", "/mnt/usrlocal"]},
            {host = 'truenas', partition = ["ERROR", "/", "/var", "/mnt/Parish_backup"]},
            {host = 'newnas', partition = ["ERROR", "/", "/var", "/mnt/chem1"]}
]


