###
# The database contains all the information about hosts and 
# partitions that this program monitors.
###
database = './dfstat.db'

###
# Location of the ssh config information
###
sshconfig_file = '~/.ssh/config'

###
# Number of seconds between polling.
###
time_interval = 3600

###
# Down reporting: this is the number of consecutive times that
# a host can be non-responsive before we report it as down.
###
num_allowed_failures = 1
message_repeat = 86340 # One minute less than a day.
failure_message = "{} is non-responsive."

###
# Number of samples in the current window.
###
window_size = 50

###
# Where to send the alarms.
###
notification_address = [ 'hpc@richmond.edu', '8044959650@vtext.com' ]

###
# Parameters for statistical analysis
###
mu = 0
sigma = 0.1
p_value = 0.05
