###
# The database contains all the information about hosts and 
# partitions that this program monitors.
###
database = './dfstat.db'

###
# Location of the ssh config information
###
sshconfig_file = '/home/alina/df_stat/myconfig'

###
# Number of seconds between polling.
###
time_interval = 3600

###
# Number of samples in the current window.
###
window_size = 50

###
# Where to send the alarms.
###
notification_address = [ 'hpc@richmond.edu', '8044959650@vtext.com' ]

###
# Parameters for statistical analysis
###
#hosts = [{"host" = 'alexis', "partition" = "ERROR"}, {"host" = 'alexis', "partition" = "/usr/local"}]

insert_statements = [
    "insert into hosts (host, partition) values ('alexis', 'ERROR');",
    "insert into hosts (host, partition) values ('alexis', '/home');",
    "insert into hosts (host, partition) values ('alexis', '/usr/local');",
    "insert into hosts (host, partition) values ('adam', 'ERROR');",
    "insert into hosts (host, partition) values ('adam', '/home');",
    "insert into hosts (host, partition) values ('adam', '/');"
]
